version: 2
updates:
  - package-ecosystem: "docker"
    directory: "railway"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "docker"
    directory: "heroku"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "docker"
    directory: "render"
    schedule:
      interval: "daily"
