version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "heroku"
      - "render"
    schedule:
      interval: "weekly"
    groups:
      coder-image:
        patterns:
          - "*"
