# Coder Servive
services:
  - type: web
    name: coder
    env: docker
    autoDeploy: false
    plan: starter
    rootDir: render
    healthCheckPath: /healthz
    envVars:
      - key: CODER_PG_CONNECTION_URL
        fromDatabase:
          name: coder
          property: connectionString
      - key: RENDER_HOST
        fromService:
          name: coder
          type: web
          property: host
      - key: CODER_WILDCARD_ACCESS_URL
        sync: false
# Postgress Datbase
databases:
  - name: coder
    postgresMajorVersion: 15
