name: coder
title: Coder
type: app
base: core24
version: '2.12.4'
summary:  Self-Hosted Cloud Development Environments
license: AGPL-3.0
contact: https://coder.com/contact
issues: https://github.com/coder/coder/issues
source-code: https://github.com/coder/coder
website: https://coder.com
description: |
  Coder is an open-source cloud development environment (CDE)
  that you host in your cloud or on-premises. With Coder, you
  can deploy environments that provide the infrastructure, IDEs,
  and tools your developers need. Upgrade to Coder Enterprise
  to gain enhanced security, governance, and observability for 
  your platform teams.
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

parts:
  coder:
    plugin: dump
    source: https://github.com/coder/coder/releases/download/v$SNAPCRAFT_PROJECT_VERSION/coder_$SNAPCRAFT_PROJECT_VERSION_linux_$CRAFT_ARCH_BUILD_FOR.tar.gz

apps:
  coder:
    command: coder
    plugs:
      - docker
      - home
      - network
      - network-bind
